version: "3.8"
services:
  mlflow:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./mlruns:/app/mlruns
    command: bash -c "pip install mlflow && mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /app/mlruns --host 0.0.0.0 --port 5000"
    ports:
      - "5000:5000"

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: always

  chatbot:
    build: ./app
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - mlflow
      - ollama

volumes:
  ollama:

